# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (Railway will override these)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recruitment_sys}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nadege33}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# FILE UPLOAD (Cloudinary) ? FIXED
# ===============================
cloudinary.cloud_name=dqmirkopr
cloudinary.api_key=923165148918649
cloudinary.api_secret=2JKyIVERGUEU-uNRutEoP_zQSyI